from django.db import models
from users.models import Teacher

class LessonPlan(models.Model):
    STATUS_CHOICES = [
        ('active', 'Active'),
        ('completed', 'Completed'),
        ('draft', 'Draft'),
    ]

    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, related_name='lesson_plans')
    title = models.CharField(max_length=255)
    subject = models.CharField(max_length=100)
    grade_level = models.CharField(max_length=50)
    topic = models.CharField(max_length=255)
    learning_objective = models.TextField()
    class_size = models.CharField(max_length=50, blank=True)
    diversity_level = models.CharField(max_length=100, blank=True)
    
    # Differentiation flags
    content_diff = models.BooleanField(default=False)
    process_diff = models.BooleanField(default=False)
    product_diff = models.BooleanField(default=False)
    environment_diff = models.BooleanField(default=False)

    # Differentiation text (generated by AI)
    differentiation_content = models.TextField(blank=True, null=True)
    differentiation_process = models.TextField(blank=True, null=True)
    differentiation_product = models.TextField(blank=True, null=True)
    differentiation_environment = models.TextField(blank=True, null=True)

    # Generated content
    duration = models.CharField(max_length=100)
    materials = models.JSONField(default=list) # List of strings
    objectives = models.JSONField(default=list) # List of strings (detailed objectives from AI)
    activities = models.JSONField(default=list) # List of dicts {tier, title, content, color}
    
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='draft')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
