# Generated by Django 6.0.5 on 2026-05-29 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=100)),
                ('grade_level', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=255)),
                ('learning_objective', models.TextField()),
                ('class_size', models.CharField(blank=True, max_length=50)),
                ('diversity_level', models.CharField(blank=True, max_length=100)),
                ('content_diff', models.BooleanField(default=False)),
                ('process_diff', models.BooleanField(default=False)),
                ('product_diff', models.BooleanField(default=False)),
                ('environment_diff', models.BooleanField(default=False)),
                ('duration', models.CharField(max_length=100)),
                ('materials', models.JSONField(default=list)),
                ('objectives', models.JSONField(default=list)),
                ('activities', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='users.teacher')),
            ],
        ),
    ]
