# Generated by Django 4.2.30 on 2026-05-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lessonplan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='differentiation_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='differentiation_environment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='differentiation_process',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='differentiation_product',
            field=models.TextField(blank=True, null=True),
        ),
    ]
