# Generated by Django 4.2.30 on 2026-05-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lessonplan_differentiation_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
