# Generated by Django 6.0.5 on 2026-05-29 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('worksheet', 'Worksheet'), ('presentation', 'Presentation'), ('video', 'Video'), ('article', 'Article'), ('other', 'Other')], max_length=20)),
                ('file_url', models.URLField(blank=True, max_length=500)),
                ('content', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('grade_level', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='users.teacher')),
            ],
        ),
    ]
